version: '3.8'

services:
  app:
    build: .
    container_name: warkopkasir-app
    restart: unless-stopped
    volumes:
      - .:/app
      - ./storage:/app/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: warkopkasir-webserver
    restart: unless-stopped
    ports:
      - "3011:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/app/public:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge