version: '3.8'

services:
  app:
    image: loyalty59/warkopkasir-frontend:latest 
    container_name: warkopkasir-frontend-app
    restart: always

  webserver:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    restart: always
